export class EntityPlatilloDetalle {

    public idMeal : any | undefined;
    public strMeal : any | undefined;
    public strDrinkAlternate: any | undefined;
    public strCategory: any | undefined;
    public strArea: any | undefined;
    public strInstructions: any | undefined;
    public strMealThumb: any | undefined;
    public strTags: any | undefined;
    public strYoutube: any | undefined;
    public strIngredient1: any | undefined;
    public strIngredient2: any | undefined;
    public strIngredient3: any | undefined;
    public strIngredient4: any | undefined;
    public strIngredient5: any | undefined;
    public strIngredient6: any | undefined;
    public strIngredient7: any | undefined;
    public strIngredient8: any | undefined;
    public strIngredient9: any | undefined;
    public strIngredient10: any | undefined;
    public strIngredient11: any | undefined;
    public strIngredient12: any | undefined;
    public strIngredient13: any | undefined;
    public strIngredient14: any | undefined;
    public strIngredient15: any | undefined;
    public strIngredient16: any | undefined;
    public strIngredient17: any | undefined;
    public strIngredient18: any | undefined;
    public strIngredient19: any | undefined;
    public strIngredient20: any | undefined;
    public strMeasure1: any | undefined;
    public strMeasure2: any | undefined;
    public strMeasure3: any | undefined;
    public strMeasure4: any | undefined;
    public strMeasure5: any | undefined;
    public strMeasure6: any | undefined;
    public strMeasure7: any | undefined;
    public strMeasure8: any | undefined;
    public strMeasure9: any | undefined;
    public strMeasure10: any | undefined;
    public strMeasure11: any | undefined;
    public strMeasure12: any | undefined;
    public strMeasure13: any | undefined;
    public strMeasure14: any | undefined;
    public strMeasure15: any | undefined;
    public strMeasure16: any | undefined;
    public strMeasure17: any | undefined;
    public strMeasure18: any | undefined;
    public strMeasure19: any | undefined;
    public strMeasure20: any | undefined;
    public strSource: any | undefined;
    public strImageSource: any | undefined;
    public strCreativeCommonsConfirmed: any | undefined;
    public dateModified: any | undefined; 
}
